/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceGrafica;

import Cliente.Cliente;
import Cliente.Solicitacao;
import bd.daos.*;

import javax.swing.JOptionPane;

/**
 *
 * @author Josiele
 */
public class LogarCliente extends javax.swing.JFrame {
	private String email;
	private String senha;
	private String host;
	private int port;

	/**
	 * Creates new form LogarCliente
	 */

	public LogarCliente(String _host, int _port) {
		initComponents();
		this.setLocationRelativeTo(null);
		host = _host;
		port = _port;

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		btnEntrar = new javax.swing.JButton();
		btnCancelar = new javax.swing.JButton();
		btnCadastrar = new javax.swing.JButton();
		txtEmail = new javax.swing.JTextField();
		txtSenha = new javax.swing.JPasswordField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("E-mail:");

		jLabel2.setText("Senha:");

		btnEntrar.setText("Entrar");
		btnEntrar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnEntrarActionPerformed(evt);
			}
		});

		btnCancelar.setText("Cancelar");
		btnCancelar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCancelarActionPerformed(evt);
			}
		});

		btnCadastrar.setText("Cadastrar-se");
		btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCadastrarActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(33, 33, 33)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 95,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 95,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(btnCadastrar))
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel1).addComponent(jLabel2))
										.addGap(34, 34, 34)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(txtEmail).addComponent(txtSenha))))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(43, 43, 43)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1).addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(25, 25, 25)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2).addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(28, 28, 28)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnEntrar).addComponent(btnCancelar).addComponent(btnCadastrar))
						.addContainerGap(21, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * Botão "Entrar": 
	 * O método quando acionado, verifica se todos os campos existentes na tela foram preenchidos.
	 * Quando preenchidos, um socket Cliente é criado e um pedido de conexão é enviado para o servidor. 
	 */	
	private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEntrarActionPerformed

		email = txtEmail.getText();
		senha = txtSenha.getText();

		if (email.equals("") || senha.equals("")) {
			JOptionPane.showMessageDialog(null, "Insira seu email e senha", "Atencao: " + "Login",
					JOptionPane.INFORMATION_MESSAGE);
		} else {
			try {
				Solicitacao solicitacao = new Solicitacao("LOG", email, senha);
				Cliente cliente = new Cliente(host, port, solicitacao);
				cliente.conectar();
				
				JOptionPane.showMessageDialog(null, cliente.getResposta().getMessage() , "Mensagem" ,
						JOptionPane.INFORMATION_MESSAGE);			
				

			} catch (Exception e) {
				System.out.println(e.getMessage());
			}
		}
	}// GEN-LAST:event_btnEntrarActionPerformed

	/**
	 * Botão "Cancelar": 
	 * O método quando acionado, apaga todos os campos da tela e pergunta se o usuário deseja sair. 
	 */
	private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelarActionPerformed
		txtEmail.setText("");
		txtSenha.setText("");
		
		int dialogResult = JOptionPane.showConfirmDialog(this, "Deseja realmente sair?", "Cancelar",
				JOptionPane.YES_NO_OPTION);
		if (dialogResult == 0)
			this.setVisible(false); 
		
	}// GEN-LAST:event_btnCancelarActionPerformed
	
	/**
	 * Botão "Cadastrar": 
	 * Permite que o usuário efetue seu cadastro.  
	 */

	private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCadastrarActionPerformed
		new CadastroCliente(host, port).setVisible(true);
	}// GEN-LAST:event_btnCadastrarActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnCadastrar;
	private javax.swing.JButton btnCancelar;
	private javax.swing.JButton btnEntrar;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JTextField txtEmail;
	private javax.swing.JPasswordField txtSenha;
	// End of variables declaration//GEN-END:variables
}
